sudo: required
services:
  - docker
dist: trusty
language: node_js
node_js:
  - "8"
notifications:
  email: false
script:
  - ./docker_build
after_success:
  # Fix permissions on node_modules after Docker creates the folder.
  - sudo chown "$(whoami)" node_modules
  - npm install coveralls
  # Fix paths in lcov.info so they match Coveralls' expectation that they were generated on Travis.
  - docker exec ingredient-demo cat /app/coverage/lcov.info | sed --expression='s@^SF:\/app@SF:'"${PWD}"'@g' | ./node_modules/coveralls/bin/coveralls.js